// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4bfotztEEEW7e4YA5ac_bW7C8CCoKZxQ',
    appId: '1:631789093574:web:159c5a29619e14f7d84dc7',
    messagingSenderId: '631789093574',
    projectId: 'geoattendance-b1176',
    authDomain: 'geoattendance-b1176.firebaseapp.com',
    storageBucket: 'geoattendance-b1176.firebasestorage.app',
    measurementId: 'G-07WLK9TGPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5-H2h51wHkaEKRJTafTUyYxdnqpBCRY',
    appId: '1:631789093574:android:a501c3c2dde3618bd84dc7',
    messagingSenderId: '631789093574',
    projectId: 'geoattendance-b1176',
    storageBucket: 'geoattendance-b1176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_OTSTwSaEs1auTyOohGh2-wPg9RC1PE',
    appId: '1:631789093574:ios:4e7ea5d0e282ca39d84dc7',
    messagingSenderId: '631789093574',
    projectId: 'geoattendance-b1176',
    storageBucket: 'geoattendance-b1176.firebasestorage.app',
    iosBundleId: 'com.example.geolocationAttendanceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_OTSTwSaEs1auTyOohGh2-wPg9RC1PE',
    appId: '1:631789093574:ios:4e7ea5d0e282ca39d84dc7',
    messagingSenderId: '631789093574',
    projectId: 'geoattendance-b1176',
    storageBucket: 'geoattendance-b1176.firebasestorage.app',
    iosBundleId: 'com.example.geolocationAttendanceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4bfotztEEEW7e4YA5ac_bW7C8CCoKZxQ',
    appId: '1:631789093574:web:46c0fb02729da11fd84dc7',
    messagingSenderId: '631789093574',
    projectId: 'geoattendance-b1176',
    authDomain: 'geoattendance-b1176.firebaseapp.com',
    storageBucket: 'geoattendance-b1176.firebasestorage.app',
    measurementId: 'G-NEHMM53R2W',
  );
}
